#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["API.Cliente/API.Cliente.csproj", "API.Cliente/"]
RUN dotnet restore "API.Cliente/API.Cliente.csproj"
COPY . .
WORKDIR "/src/API.Cliente"
RUN dotnet build "API.Cliente.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "API.Cliente.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "API.Cliente.dll"]